# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: es2vec_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'es2vec_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65s2vec_search.proto\x12\tes2vec.v1\"\xd3\x02\n\x13HybridSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\t\x12\t\n\x01k\x18\x03 \x01(\x05\x12\x13\n\x0bmatch_field\x18\x04 \x01(\t\x12\x14\n\x07use_rrf\x18\x05 \x01(\x08H\x00\x88\x01\x01\x12\x1a\n\rvector_weight\x18\x06 \x01(\x01H\x01\x88\x01\x01\x12\x1b\n\x0ekeyword_weight\x18\x07 \x01(\x01H\x02\x88\x01\x01\x12\x13\n\x06kw_sat\x18\x08 \x01(\x01H\x03\x88\x01\x01\x12\x1e\n\x11keyword_norm_mode\x18\t \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0bname_rerank\x18\n \x01(\x08H\x05\x88\x01\x01\x42\n\n\x08_use_rrfB\x10\n\x0e_vector_weightB\x11\n\x0f_keyword_weightB\t\n\x07_kw_satB\x14\n\x12_keyword_norm_modeB\x0e\n\x0c_name_rerank\"\xac\x01\n\tSearchHit\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x16\n\x0etext_truncated\x18\x05 \x01(\x08\x12\x17\n\nchapter_id\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x63hunk_index\x18\x07 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_chapter_idB\x0e\n\x0c_chunk_index\"y\n\x14HybridSearchResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x10\n\x08returned\x18\x04 \x01(\x05\x12\"\n\x04hits\x18\x05 \x03(\x0b\x32\x14.es2vec.v1.SearchHit\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9f\x01\n\rSearchService\x12O\n\x0cHybridSearch\x12\x1e.es2vec.v1.HybridSearchRequest\x1a\x1f.es2vec.v1.HybridSearchResponse\x12=\n\x06Health\x12\x18.es2vec.v1.HealthRequest\x1a\x19.es2vec.v1.HealthResponseB\x03\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'es2vec_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
  _globals['_HYBRIDSEARCHREQUEST']._serialized_start=35
  _globals['_HYBRIDSEARCHREQUEST']._serialized_end=374
  _globals['_SEARCHHIT']._serialized_start=377
  _globals['_SEARCHHIT']._serialized_end=549
  _globals['_HYBRIDSEARCHRESPONSE']._serialized_start=551
  _globals['_HYBRIDSEARCHRESPONSE']._serialized_end=672
  _globals['_HEALTHREQUEST']._serialized_start=674
  _globals['_HEALTHREQUEST']._serialized_end=689
  _globals['_HEALTHRESPONSE']._serialized_start=691
  _globals['_HEALTHRESPONSE']._serialized_end=723
  _globals['_SEARCHSERVICE']._serialized_start=726
  _globals['_SEARCHSERVICE']._serialized_end=885
_builder.BuildServices(DESCRIPTOR, 'es2vec_search_pb2', _globals)
# @@protoc_insertion_point(module_scope)
